name: Build and publish python package

on:
  release:
    types: [published]

jobs:
  bump-package-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install poetry
        run: pip install poetry

      - name: Bump the version
        run: poetry version patch

      - name: Create branch
        run: |
          git checkout -b version-bump-${{ github.run_number }}
          git branch # Verify the new branch is created

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add pyproject.toml
          git commit -m "Bump version"
          git push --set-upstream origin version-bump-${{ github.run_number }}

  publish-service-client-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install poetry
        run: pip install poetry

      - name: Build and publish package
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry build
          poetry publish
        env:
          POETRY_REPOSITORY_URL: "https://upload.pypi.org/legacy/"

      - name: Clean up build artifacts
        run: poetry env remove 3.11
