name: Build and publish python package

on:
  release:
    types: [published]

jobs:
  publish-service-client-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        - name: Check out the repo
          uses: actions/checkout@v4

        - name: Build and publish to pypi
          uses: JRubics/poetry-publish@v1.17
          with:
            python_version: "3.11"
            poetry_version: "==1.7.1" # (PIP version specifier syntax)
            pypi_token: ${{ secrets.PYPI_TOKEN }}
            build_format: "sdist"
            allow_poetry_pre_release: "yes"
            ignore_dev_requirements: "yes"
