name: Build and publish python package

on:
  push:
    branches: [main]

jobs:
  install-python:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: 'pyproject.toml' # Read python version from a file pyproject.toml

      - name: Install poetry
        run: pip install poetry

      - name: Bump the version
        run: poetry version patch

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add pyproject.toml
          git commit -am "actions: bump package version"
          git push

      - name: Build and publish package
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry build
          poetry publish

      - name: Clean up build artifacts
        run: poetry env remove --all
